### PR TITLE
Added a bunch of extensions that previously lived at cburgdorf/rxjs-contribute

### PR DESCRIPTION
**Pull request by cburgdorf**
The commit includes MIT license.txt (I omitted a copyright note, not sure if this should be Microsoft?) and vsdocs

### CODE REVIEW

**Comment by cburgdorf** [comment]
Oops, just noticed that there are still copyrights that show my name in there. Will fix that

**Comment by mattpodwysocki** [comment]
Done!

**Comment by cburgdorf** [comment]
Cool stuff, thanks. Just noticced tha ForkJoin is in there, too. Thats in the latest experimantial as well, isnt it? Should we remove this?

**Comment by mattpodwysocki** [comment]
Yes, we should remove that.  I need to see what's in Rxx that we can bring over as well.

**Pull request merged**
